/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OrgArquivos;

import Computador.CadPc;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ti
 */
public class FormPesqInfoArq extends javax.swing.JFrame {

    ArquivosInfo info = new ArquivosInfo("Dados.txt");

    /**
     * Creates new form FormPesqInfoArq
     */
    public FormPesqInfoArq() {
        initComponents();
       initabela();
  
    }
    
    public  void initabela(){
     DefaultTableModel modelo = (DefaultTableModel) tbArqPesq.getModel();
        modelo.setNumRows(0);

        for (ArquivoDados dados : info.getInfoArquivos()) {
            modelo.addRow(new Object[]{dados.getNumCadastro(), dados.getNomeArq(), dados.getCaminhoOriginal(),
                dados.getCaminhoFinal(), dados.getDescrocao(),dados.getDataBackup()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbArqPesq = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnPesq = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tbArqPesq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cadastro", "Nome arquivo", "Caminho Original", "Caminho Final", "Descrição", "Data Cad"
            }
        ));
        tbArqPesq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbArqPesqMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbArqPesq);

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnPesq.setText("Pesquisa");
        btnPesq.setFocusable(false);
        btnPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesq)
                .addGap(438, 438, 438))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btnPesq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbArqPesqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbArqPesqMouseClicked
        // TODO add your handling code here:

        int numCad = (Integer) tbArqPesq.getValueAt(tbArqPesq.getSelectedRow(), 0);

        System.out.println(numCad);

        JPanel myPanel = new JPanel();
        JDialog teste = new JDialog();
        JButton alt = new JButton("Alterar Dados");
        JButton del = new JButton("Deletar Dado");

        myPanel.add(alt);
        myPanel.add(del);
        teste.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        teste.getContentPane().add(myPanel);
        teste.pack();
        teste.setLocationRelativeTo(null);
        teste.setVisible(true);

        del.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                info.deleteInfoArq(numCad);
                initabela();
            }
        });
        
        
        alt.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JTextField camp = new JTextField(10);
                JTextField alt = new JTextField(20);

                JPanel myPanel = new JPanel();
                
                myPanel.add(new JLabel("Campo"));
                myPanel.add(camp);
                myPanel.add(Box.createVerticalStrut(10)); // a spacer
                myPanel.add(new JLabel("Alteração"));
                myPanel.add(alt);
                
                 
                System.out.println(alt.getText() + " " + camp.getText());
                int result = JOptionPane.showConfirmDialog(null, myPanel,
                        "Preencha os Campos", JOptionPane.OK_CANCEL_OPTION);
                if (result == JOptionPane.OK_OPTION) {

                   if( info.alterInfos(numCad, alt.getText(), camp.getText())){
                      
                       initabela();
                   }
                   else
                       JOptionPane.showMessageDialog(null, "deu ruim");
                } else {
                    JOptionPane.showMessageDialog(null, "Operação cancelada");
                }
            }
        });

    }//GEN-LAST:event_tbArqPesqMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FormOrgArquivos novoArq = new FormOrgArquivos();
        novoArq.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqActionPerformed
        // TODO add your handling code here:
        initabela();
    }//GEN-LAST:event_btnPesqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPesqInfoArq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPesqInfoArq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPesqInfoArq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPesqInfoArq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPesqInfoArq().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesq;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbArqPesq;
    // End of variables declaration//GEN-END:variables
}
