/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Computador;

import Licencas.LicencaDAO;
import Licencas.LicencaDados;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ti
 */
public class CadPc extends javax.swing.JFrame {

    /**
     * Creates new form CadPc
     */
    public CadPc() {
        initComponents();
        txtLicenca.setVisible(false);
        lblLicenca.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNomeComputador = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCPU = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtGPU = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRam = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAnyDesk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcadPc = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        txtSenhaAnyDesk = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        txtQtdMaquinas = new javax.swing.JTextField();
        lblPergunta = new javax.swing.JLabel();
        txtLicenca = new javax.swing.JTextField();
        cbSim = new javax.swing.JRadioButton();
        cbNao = new javax.swing.JRadioButton();
        lblLicenca = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });

        jLabel1.setText("Nome Do Computador");

        jLabel2.setText("CPU");

        jLabel3.setText("GPU");

        jLabel4.setText("RAM");

        jLabel5.setText("AnyDesk");

        jLabel6.setText("Senha AnyDesk");

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        tbcadPc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Computador", "Usuário", "Processador", "Placa de Video", "Memória RAM", "Número AnyDesk", "Senha AnyDesk"
            }
        ));
        tbcadPc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbcadPcMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbcadPc);

        jLabel7.setText("Nome Computador");

        jLabel8.setText("Quantidade de máquinas");

        txtQtdMaquinas.setEditable(false);
        txtQtdMaquinas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtQtdMaquinas.setForeground(new java.awt.Color(255, 51, 51));
        txtQtdMaquinas.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQtdMaquinas.setBorder(null);

        lblPergunta.setText("Software com licença?");

        buttonGroup1.add(cbSim);
        cbSim.setText("Sim");
        cbSim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbSimMouseClicked(evt);
            }
        });
        cbSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSimActionPerformed(evt);
            }
        });

        buttonGroup1.add(cbNao);
        cbNao.setText("Não");
        cbNao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbNaoMouseClicked(evt);
            }
        });
        cbNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNaoActionPerformed(evt);
            }
        });

        lblLicenca.setText("Chave || Acesso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(cbSim)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbNao))
                                .addComponent(lblPergunta)
                                .addComponent(txtSenhaAnyDesk, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                .addComponent(txtNomeComputador, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCPU, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtGPU, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtRam, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAnyDesk, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtLicenca, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(lblLicenca))))))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar)
                        .addGap(89, 89, 89)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtdMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisar)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(txtQtdMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtNomeComputador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAnyDesk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSenhaAnyDesk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPergunta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbSim)
                            .addComponent(cbNao))
                        .addGap(12, 12, 12)
                        .addComponent(lblLicenca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtLicenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCadastrar)
                            .addComponent(btnLimpar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAlterar)
                            .addComponent(btnSair))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:

        computadorDao dao = new computadorDao();

        String nomeComputador = txtNomeComputador.getText();
        String processador = txtCPU.getText();
        String placaDeVideo = txtGPU.getText();
        String RAM = txtRam.getText();
        String numeroAnyDesk = txtAnyDesk.getText();
        String senhaAnyDesk = txtSenhaAnyDesk.getText();

        boolean nomePcValido = (nomeComputador != null);

        boolean processadorValido = processador != null;

        boolean placaDeVideoValida = placaDeVideo != null;

        boolean ramValida = (RAM != null) && RAM.trim().length() < 200;

        boolean numeroAnyDeskValido = (numeroAnyDesk != null) && (numeroAnyDesk.trim().length() == 9) && (numeroAnyDesk.matches("[0-9]+"));

        boolean senhaAnyDeskValida = (senhaAnyDesk != null) && (senhaAnyDesk.trim().length() == 9);

        boolean camposValidos = nomePcValido && placaDeVideoValida && processadorValido && ramValida && numeroAnyDeskValido && numeroAnyDeskValido && senhaAnyDeskValida;
        if (!camposValidos) {
            if (!nomePcValido) {
                JOptionPane.showMessageDialog(null, "Nome do computador não é válida");
            }

            if (!processadorValido) {
                JOptionPane.showMessageDialog(null, "Nome do Processador inválido ou nulo");
            }

            if (!placaDeVideoValida) {
                JOptionPane.showMessageDialog(null, "Nome da placa de video inválido ou nulo");
            }

            if (!ramValida) {
                JOptionPane.showMessageDialog(null, "Nome da RAM inválida ou nulo");
            }

            if (!numeroAnyDeskValido) {
                JOptionPane.showMessageDialog(null, "Número do AnyDesk inválido ou nulo");
            }

            if (!senhaAnyDeskValida) {
                JOptionPane.showMessageDialog(null, "Senha do AnyDesk inválida ou nula");
            }

        } else {

            try {
                LicencaDAO daoli = new LicencaDAO();
                LicencaDados li1 = new LicencaDados();
                 //System.out.println(txtLicenca.getText());
                String NomeLi = li1.getNomeLicenca(txtLicenca.getText());
                System.out.println(NomeLi);


                if (cbSim.isSelected()) {
                    if (NomeLi == "-1") {
                        JOptionPane.showMessageDialog(null, "Licença Incorreta");
                    } else {
                     LicencaDados   li = new LicencaDados(NomeLi, txtLicenca.getText(), txtNomeComputador.getText(), txtCPU.getText(), txtGPU.getText(), Integer.parseInt(txtRam.getText()),
                                Integer.parseInt(txtAnyDesk.getText()), txtSenhaAnyDesk.getText());

                        daoli.AddPcLicenca(li);
                    }
                } else if (cbNao.isSelected()) {
                    DadosPc pc = new DadosPc(nomeComputador, processador, placaDeVideo,
                            Integer.parseInt(RAM), Integer.parseInt(numeroAnyDesk), senhaAnyDesk);

                    dao.addComputador(pc);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }

            txtAnyDesk.setText("");
            txtCPU.setText("");
            txtGPU.setText("");
            txtNomeComputador.setText("");
            txtRam.setText("");
            txtSenhaAnyDesk.setText("");

        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:

        String nomeComputador = txtPesquisar.getText();
        String cpu = txtCPU.getText();
        String gpu = txtGPU.getText();
        String ram = txtRam.getText();
        String numeroAnyDesk = txtAnyDesk.getText();

        if (nomeComputador.trim().length() > 0) {
            int i = 0;
            DefaultTableModel modelo = (DefaultTableModel) tbcadPc.getModel();
            modelo.setNumRows(0);

            computadorDao dao = new computadorDao();

            for (DadosPc pc : dao.findComputer(nomeComputador)) {
                modelo.addRow(new Object[]{pc.getNomePc(), "0", pc.getCpu(), pc.getGpu(), pc.getRam(), pc.getNumeroAnyDesk(), pc.getSenhaAnyDesk(),});
                i++;
            }
            txtQtdMaquinas.setText(String.valueOf(i));
        } else if (cpu.trim().length() > 0 && gpu.trim().length() == 0) {
            int i = 0;
            DefaultTableModel modelo = (DefaultTableModel) tbcadPc.getModel();
            modelo.setNumRows(0);

            computadorDao dao = new computadorDao();

            for (DadosPc pc : dao.findComputerByCpu(cpu)) {
                modelo.addRow(new Object[]{pc.getNomePc(), "0", pc.getCpu(), pc.getGpu(), pc.getRam(), pc.getNumeroAnyDesk(), pc.getSenhaAnyDesk(),});
                i++;
            }
            txtQtdMaquinas.setText(String.valueOf(i));

        } else if (gpu.trim().length() > 0 && cpu.trim().length() == 0) {
            int i = 0;
            DefaultTableModel modelo = (DefaultTableModel) tbcadPc.getModel();
            modelo.setNumRows(0);

            computadorDao dao = new computadorDao();

            for (DadosPc pc : dao.findComputerByGpu(gpu)) {
                modelo.addRow(new Object[]{pc.getNomePc(), "0", pc.getCpu(), pc.getGpu(), pc.getRam(), pc.getNumeroAnyDesk(), pc.getSenhaAnyDesk(),});
                i++;
            }
            txtQtdMaquinas.setText(String.valueOf(i));

        } else if (ram.trim().length() > 0) {
            int i = 0;

            DefaultTableModel modelo = (DefaultTableModel) tbcadPc.getModel();
            modelo.setNumRows(0);

            computadorDao dao = new computadorDao();

            for (DadosPc pc : dao.findComputerByRam(ram)) {
                modelo.addRow(new Object[]{pc.getNomePc(), "0", pc.getCpu(), pc.getGpu(), pc.getRam(), pc.getNumeroAnyDesk(), pc.getSenhaAnyDesk(),});
                i++;
            }
            txtQtdMaquinas.setText(String.valueOf(i));

        } else if (numeroAnyDesk.trim().length() > 0) {
            int i = 0;
            DefaultTableModel modelo = (DefaultTableModel) tbcadPc.getModel();
            modelo.setNumRows(0);

            computadorDao dao = new computadorDao();

            for (DadosPc pc : dao.findComputerByAnyDesk(numeroAnyDesk)) {
                modelo.addRow(new Object[]{pc.getNomePc(), "0", pc.getCpu(), pc.getGpu(), pc.getRam(), pc.getNumeroAnyDesk(), pc.getSenhaAnyDesk(),});
                i++;
            }

            txtQtdMaquinas.setText(String.valueOf(i));

        } else if (cpu.trim().length() > 0 && gpu.trim().length() > 0) {
            int i = 0;
            DefaultTableModel modelo = (DefaultTableModel) tbcadPc.getModel();
            modelo.setNumRows(0);

            computadorDao dao = new computadorDao();

            for (DadosPc pc : dao.findComputerByAnyCpuAndGpu(cpu, gpu)) {
                modelo.addRow(new Object[]{pc.getNomePc(), "0", pc.getCpu(), pc.getGpu(), pc.getRam(), pc.getNumeroAnyDesk(), pc.getSenhaAnyDesk(),});
                i++;
            }
            txtQtdMaquinas.setText(String.valueOf(i));

        } else {

            int i = 0;
            DefaultTableModel modelo = (DefaultTableModel) tbcadPc.getModel();
            modelo.setNumRows(0);

            computadorDao dao = new computadorDao();

            for (DadosPc pc : dao.find()) {
                modelo.addRow(new Object[]{pc.getNomePc(), "0", pc.getCpu(), pc.getGpu(), pc.getRam(), pc.getNumeroAnyDesk(), pc.getSenhaAnyDesk(),});
                i++;

            }
            txtQtdMaquinas.setText(String.valueOf(i));

        }

        txtAnyDesk.setText("");
        txtCPU.setText("");
        txtGPU.setText("");
        txtNomeComputador.setText("");
        txtPesquisar.setText("");
        txtRam.setText("");
        txtSenhaAnyDesk.setText("");
        txtNomeComputador.enable(true);

        //txtNomeEmpresa.setText((String) TableFornecedores.getValueAt(TableFornecedores.getSelectedRow(),0));
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void tbcadPcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbcadPcMouseClicked
        // TODO add your handling code here:
        txtNomeComputador.setText((String) tbcadPc.getValueAt(tbcadPc.getSelectedRow(), 0));
        txtCPU.setText((String) tbcadPc.getValueAt(tbcadPc.getSelectedRow(), 2));
        txtGPU.setText((String) tbcadPc.getValueAt(tbcadPc.getSelectedRow(), 3));
        txtRam.setText(String.valueOf(tbcadPc.getValueAt(tbcadPc.getSelectedRow(), 4)));
        txtAnyDesk.setText(String.valueOf(tbcadPc.getValueAt(tbcadPc.getSelectedRow(), 5)));
        txtSenhaAnyDesk.setText(String.valueOf(tbcadPc.getValueAt(tbcadPc.getSelectedRow(), 6)));

        txtNomeComputador.enable(false);
    }//GEN-LAST:event_tbcadPcMouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        DadosPc pc = new DadosPc();
        computadorDao dao = new computadorDao();

        String nomeComputador = txtNomeComputador.getText();
        String processador = txtCPU.getText();
        String placaDeVideo = txtGPU.getText();
        String RAM = txtRam.getText();
        String numeroAnyDesk = txtAnyDesk.getText();
        String senhaAnyDesk = txtSenhaAnyDesk.getText();
        try {
            pc.setNomePc(nomeComputador);
            pc.setCpu(processador);
            pc.setGpu(placaDeVideo);
            pc.setRam(Integer.parseInt(RAM));
            pc.setNumeroAnyDesk(Integer.parseInt(numeroAnyDesk));
            pc.setSenhaAnyDesk(senhaAnyDesk);
            dao.Update(pc);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        txtNomeComputador.enable(true);
        txtAnyDesk.setText("");
        txtCPU.setText("");
        txtGPU.setText("");
        txtNomeComputador.setText("");
        txtPesquisar.setText("");
        txtRam.setText("");
        txtSenhaAnyDesk.setText("");
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        txtAnyDesk.setText("");
        txtCPU.setText("");
        txtGPU.setText("");
        txtNomeComputador.setText("");
        txtPesquisar.setText("");
        txtRam.setText("");
        txtSenhaAnyDesk.setText("");

        txtNomeComputador.enable(true);
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseMoved

    private void cbNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNaoActionPerformed

    private void cbNaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbNaoMouseClicked
        // TODO add your handling code here:

        if (cbNao.isSelected()) {

            txtLicenca.setVisible(false);
            lblLicenca.setVisible(false);
        }
    }//GEN-LAST:event_cbNaoMouseClicked

    private void cbSimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbSimMouseClicked
        // TODO add your handling code here:
        if (cbSim.isSelected()) {

            txtLicenca.setVisible(true);
            lblLicenca.setVisible(true);
        }
    }//GEN-LAST:event_cbSimMouseClicked

    private void cbSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSimActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_cbSimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadPc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadPc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cbNao;
    private javax.swing.JRadioButton cbSim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLicenca;
    private javax.swing.JLabel lblPergunta;
    private javax.swing.JTable tbcadPc;
    private javax.swing.JTextField txtAnyDesk;
    private javax.swing.JTextField txtCPU;
    private javax.swing.JTextField txtGPU;
    private javax.swing.JTextField txtLicenca;
    private javax.swing.JTextField txtNomeComputador;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtQtdMaquinas;
    private javax.swing.JTextField txtRam;
    private javax.swing.JPasswordField txtSenhaAnyDesk;
    // End of variables declaration//GEN-END:variables
}
